<?php
namespace Database\Seeders; use App\Models\WaterEconomyBarangay; use Illuminate\Database\Seeder; use Illuminate\Support\Facades\File;
class WaterEconomySeeder extends Seeder {
    public function run(): void {$json=json_decode(File::get(database_path('data/water_economy_dataset_v3_238_barangays_sectors.json')),true,512,JSON_THROW_ON_ERROR); foreach($json['barangays'] as $r){$pop=(int)($r['population_2024_psa']??0);$ahs=(float)($r['avg_household_size_2020_psa_lgu']??4.5);$hh=((float)($r['basic_domestic_demand_lpd_estimated']??0))/1000;$ag=(float)($r['agriculture_simulated']['water_demand_m3_day']??0);$fi=(float)($r['fisheries_simulated']['water_demand_m3_day']??0);$aq=(float)($r['aquaculture_simulated']['water_demand_m3_day']??0);$bu=(float)($r['business_simulated']['water_demand_m3_day']??0);$crit=max(5,$pop*0.003);$total=$hh+$crit+$ag+$fi+$aq+$bu;$gross=$total>0?$total/0.70:0;$cap=$total>0?$total/0.85:0; WaterEconomyBarangay::updateOrCreate(['psgc_code'=>$r['psgc_code']],[
'lgu'=>$r['lgu'],'barangay'=>$r['barangay'],'urban_rural'=>$r['urban_rural_psa']??null,'population_2024'=>$pop,'avg_household_size'=>$ahs,'gross_supply_m3_day'=>round($gross,2),'source_capacity_m3_day'=>round($cap,2),'nrw_rate_pct'=>25,'reserve_rate_pct'=>5,'tariff_php_m3'=>30,'avg_household_income_php'=>(float)($r['avg_household_income_php_simulated']??0),'monthly_water_cost_php'=>(float)($r['avg_monthly_water_cost_php_simulated']??0),'piped_access_pct'=>(float)($r['piped_access_pct_simulated']??0),'supply_reliability_pct'=>(float)($r['supply_reliability_pct_simulated']??0),'livelihood_profile'=>$r['livelihood_profile_simulated']??null,
'household_demand_m3_day'=>round($hh,2),'critical_services_demand_m3_day'=>round($crit,2),'agriculture_demand_m3_day'=>round($ag,2),'fisheries_demand_m3_day'=>round($fi,2),'aquaculture_demand_m3_day'=>round($aq,2),'business_demand_m3_day'=>round($bu,2),'industry_demand_m3_day'=>0,
'household_allocated_m3_day'=>round($hh,2),'critical_services_allocated_m3_day'=>round($crit,2),'agriculture_allocated_m3_day'=>round($ag,2),'fisheries_allocated_m3_day'=>round($fi,2),'aquaculture_allocated_m3_day'=>round($aq,2),'business_allocated_m3_day'=>round($bu,2),'industry_allocated_m3_day'=>0,
'sector_meta'=>['agriculture'=>$r['agriculture_simulated']??[],'fisheries'=>$r['fisheries_simulated']??[],'aquaculture'=>$r['aquaculture_simulated']??[],'business'=>$r['business_simulated']??[]],
'data_status'=>['population_2024'=>'ACTUAL / PSA-backed','avg_household_size'=>'HISTORICAL / PSA 2020 LGU average','household_demand'=>'ESTIMATED / 55 L/person/day prototype baseline','gross_supply'=>'SIMULATED / USER-EDITABLE','source_capacity'=>'SIMULATED / USER-EDITABLE','nrw_rate'=>'SIMULATED / USER-EDITABLE','reserve_rate'=>'SIMULATED / USER-EDITABLE','tariff'=>'SIMULATED / USER-EDITABLE','sector_demands'=>'SIMULATED / USER-EDITABLE','sector_allocations'=>'SIMULATED / USER-EDITABLE','economic_fields'=>'SIMULATED']]); }} }
