<?php

namespace App\Http\Controllers;

use App\Models\WaterEconomyBarangay;
use App\Services\DecisionSnapshotService;
use App\Services\InterventionValuationService;
use App\Services\WaterEconomyCalculator;
use App\Services\PublicBenefitPerPesoService;
use Illuminate\Support\Facades\Http;


class DecisionSnapshotController extends Controller
{
    public function show(
        string $psgcCode,
        DecisionSnapshotService $snapshotService,
        WaterEconomyCalculator $calculator,
        InterventionValuationService $valuationService
    ) {
        $barangay =
            WaterEconomyBarangay::where(
                'psgc_code',
                $psgcCode
            )->firstOrFail();

        $snapshot =
            $snapshotService->build(
                $barangay,
                $calculator,
                $valuationService
            );

        return response()->json([
            'snapshot' =>
                $snapshot,
        ]);
    }

    public function aiRewrite(
        string $psgcCode,
        DecisionSnapshotService $snapshotService,
        WaterEconomyCalculator $calculator,
        InterventionValuationService $valuationService
    ) {
        $barangay =
            WaterEconomyBarangay::where(
                'psgc_code',
                $psgcCode
            )->firstOrFail();

        /*
        |--------------------------------------------------------------------------
        | CALCULATE FIRST
        |--------------------------------------------------------------------------
        */

        $snapshot =
           $snapshotService->build(
    $barangay,
    $calculator,
    $valuationService,
    $benefitService
);

        /*
        |--------------------------------------------------------------------------
        | THEN LET AI REWRITE ONLY
        |--------------------------------------------------------------------------
        */

        $system = <<<'PROMPT'
You are DALOY, the AI decision assistant for a Water Economics Decision Support System.

You are rewriting a Decision Snapshot that was already generated by deterministic calculation engines.

RULES:
- Do not invent, alter, recalculate, or replace any number.
- Do not invent a project.
- Use only the supplied structured snapshot.
- Keep the meaning of the calculated snapshot unchanged.
- Your job is concise explanation only.
- Mention the strongest current trade-off.
- Give 1 to 3 short reasons.
- State the trade-off/cost.
- State the confidence label exactly as supplied.
- Do not claim that AI made the decision.
- Do not use markdown tables.
- Keep the response compact and presentation-ready.

Return JSON only in this shape:
{
  "headline": "short sentence",
  "why": ["reason 1", "reason 2"],
  "tradeoff": "short trade-off sentence",
  "confidence": "exact supplied confidence label"
}
PROMPT;

        $response =
            Http::withToken(
                env('GROQ_API_KEY')
            )
                ->acceptJson()
                ->timeout(45)
                ->post(
                    'https://api.groq.com/openai/v1/chat/completions',
                    [
                        'model' =>
                            'openai/gpt-oss-20b',

                        'messages' => [
                            [
                                'role' =>
                                    'system',

                                'content' =>
                                    $system,
                            ],
                            [
                                'role' =>
                                    'user',

                                'content' =>
                                    json_encode(
                                        $snapshot,
                                        JSON_UNESCAPED_UNICODE |
                                        JSON_UNESCAPED_SLASHES
                                    ),
                            ],
                        ],

                        'temperature' =>
                            0.05,

                        'max_completion_tokens' =>
                            350,

                        'reasoning_effort' =>
                            'low',

                        'include_reasoning' =>
                            false,
                    ]
                );

        if ($response->failed()) {
            return response()->json([
                'message' =>
                    'AI rewrite failed.',

                'snapshot' =>
                    $snapshot,

                'status' =>
                    $response->status(),

                'details' =>
                    $response->body(),
            ], $response->status());
        }

        $content =
            trim(
                (string) $response->json(
                    'choices.0.message.content'
                )
            );

        /*
        | Remove accidental fenced JSON if the model adds it.
        */
        $content = preg_replace(
            '/^```json\s*|\s*```$/i',
            '',
            $content
        );

        $decoded =
            json_decode(
                $content,
                true
            );

        if (!is_array($decoded)) {
            return response()->json([
                'snapshot' =>
                    $snapshot,

                'ai' => [
                    'headline' =>
                        $snapshot[
                            'strongest_current_tradeoff'
                        ],

                    'why' =>
                        array_values(
                            array_map(
                                fn ($item) =>
                                    $item['text'],
                                $snapshot['why']
                            )
                        ),

                    'tradeoff' =>
                        $snapshot[
                            'tradeoff'
                        ],

                    'confidence' =>
                        $snapshot[
                            'confidence'
                        ]['label'],
                ],

                'ai_fallback' =>
                    true,
            ]);
        }

        /*
        | Force confidence to the deterministic value.
        | AI is not allowed to change it.
        */
        $decoded['confidence'] =
            $snapshot[
                'confidence'
            ]['label'];

        return response()->json([
            'snapshot' =>
                $snapshot,

            'ai' =>
                $decoded,

            'ai_fallback' =>
                false,
        ]);
    }
}
